version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lisenmi-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo'
    container_name: lisenmi-mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
volumes:
  data:
